### ISSUE TITLE
Why capatalize the Ingredients function?

### ISSUE THREAD

**Issue by joostf** [KoenHaagsma/Food-Finder#6]
https://github.com/KoenHaagsma/Food-Finder/blob/3b230e3bc2d04f9463ffe861d7d7abafdd98ba77/scripts/components/Ingredients.js#L4

It's not a constructor, is it?

**Comment by KoenHaagsma** [comment]
Can be lowercase, it's not a constructor correct.

**Comment by KoenHaagsma** [comment]
Fixed want ik gebruik deze functie niet meer
